# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */6 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics-left-part:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: left.svg
          user: fllesser
          template: classic
          base: header
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: text, json
          plugin_languages_colors: github

  github-metrics-right-part:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: right.svg
          user: fllesser
          template: classic
          base: 
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          #plugin_isocalendar_duration: full-year

  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          COMMIT_MESSAGE: "🌈 Updated waka-readme graph with new metrics"


  # update-readme:
  #   name: WakaReadme DevMetrics
  #   runs-on: ubuntu-latest
  #   steps:
  #       # this action name
  #     - uses: athul/waka-readme@master # do NOT replace with anything else
  #       with:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional if on profile readme
  #         WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
  #         ### meta
  #         API_BASE_URL: https://wakatime.com/api # optional
  #         REPOSITORY: fllesser/fllesser # optional
  #         ### content
  #         SHOW_TITLE: false # optional
  #         SECTION_NAME: waka # optional
  #         BLOCKS: ░▒▓█ # optional
  #         CODE_LANG: ruby # optional
  #         TIME_RANGE: all_time # optional
  #         LANG_COUNT: 10 # optional
  #         SHOW_TIME: true # optional
  #         SHOW_TOTAL: false # optional
  #         SHOW_MASKED_TIME: false # optional
  #         #STOP_AT_OTHER: true # optional
  #         IGNORED_LANGUAGES: YAML TOML JSON Text # optional
  #         ### commit
  #         COMMIT_MESSAGE: 🌈 Updated waka-readme graph with new metrics # optional
  #         TARGET_BRANCH: main # optional
  #         TARGET_PATH: README.md # optional
  #         COMMITTER_NAME: GitHubActionBot # optional
  #         COMMITTER_EMAIL: action-bot@github.com # optional

  #         # you can populate email-id with secrets instead